### ISSUE TITLE
Add python2 to build pipeline

### ISSUE THREAD

**Issue by AltTesterBot** [alttester/AltTester-Unity-SDK#349]
Support for python 2 pipelines is blocked by https://gitlab.com/altom/altunity/altunitytester/-/issues/364 .
```
.initialize_py2_venv: &initialize_py2_venv
  - >
    if [ -d altunitytests-py2 ]; then
      echo "Activating virtual environment."
      source altunitytests-py2/bin/activate
      echo "Virtual environment has been activated."
    else
      echo "Creating virtual environment."
      VIRTUALENV_OVERRIDE_APP_DATA=./altunitytests-py2 python2 -m virtualenv altunitytests-py2
      source altunitytests-py2/bin/activate
      echo "Virtual environment has been created and activated."
    fi
```

```
.pip2_install_dependencies: &pip2_install_dependencies
  - python2 -m pip install Appium-Python-Client
  - python2 -m pip uninstall --yes altunityrunner || true
  - python2 -m pip install -e "Bindings~/python"
  - python2 -m pip install Deprecated
  - sleep 30
```

```
run-python-2-android-tests:
  stage: test
  tags:
    - android
  script:
    - *reinstall_and_start_android_app
    - *initialize_py2_venv
    - *pip2_install_dependencies
    - python2 "Bindings~/python_bindings_tests.py"
  needs: ["build-apk"]
```

---
<sub>You can find the original issue from GitLab [here](https://gitlab.com/altom/altunity/altunitytester/-/issues/363).</sub>
